/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Confetti: typeof import('./docs/.vitepress/theme/components/confetti.vue')['default']
    FoodRecommend: typeof import('./docs/.vitepress/theme/components/food-recommend.vue')['default']
    RainbowGradient: typeof import('./docs/.vitepress/theme/components/rainbow-gradient.vue')['default']
    Ribbon: typeof import('./docs/.vitepress/theme/components/ribbon.vue')['default']
  }
}
