/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./.vitepress/theme/components/@gysm/chat/input/base.vue')['default']
    CalendarCard: typeof import('./.vitepress/theme/components/calendar-card.vue')['default']
    Chat: typeof import('./.vitepress/theme/components/@gysm/chat/index.vue')['default']
    ChatInput: typeof import('./.vitepress/theme/components/@gysm/chat/input/chat-input.vue')['default']
    ChildComponent: typeof import('./.vitepress/theme/components/ChildComponent.vue')['default']
    Code: typeof import('./.vitepress/theme/components/code.vue')['default']
    CodeLine: typeof import('./.vitepress/theme/components/code-line.vue')['default']
    Confetti: typeof import('./.vitepress/theme/components/confetti.vue')['default']
    Conversation: typeof import('./.vitepress/theme/components/@gysm/chat/conversation.vue')['default']
    CustomBanner: typeof import('./.vitepress/theme/components/custom-banner.vue')['default']
    CustomMessage: typeof import('./.vitepress/theme/components/@gysm/chat/message/expand/custom-message.vue')['default']
    DsMessage: typeof import('./.vitepress/theme/components/@gysm/chat/message/ds-message.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTag: typeof import('element-plus/es')['ElTag']
    FoodRecommend: typeof import('./.vitepress/theme/components/food-recommend.vue')['default']
    Mermaid: typeof import('./.vitepress/theme/components/mermaid.vue')['default']
    Message: typeof import('./.vitepress/theme/components/@gysm/chat/message/message.vue')['default']
    MessageList: typeof import('./.vitepress/theme/components/@gysm/chat/message/message-list.vue')['default']
    NavCategory: typeof import('./.vitepress/theme/components/navigation/nav-category.vue')['default']
    Navigation: typeof import('./.vitepress/theme/components/navigation.vue')['default']
    NavItem: typeof import('./.vitepress/theme/components/navigation/nav-item.vue')['default']
    RainbowGradient: typeof import('./.vitepress/theme/components/rainbow-gradient.vue')['default']
    Ribbon: typeof import('./.vitepress/theme/components/ribbon.vue')['default']
    Session: typeof import('./.vitepress/theme/components/@gysm/chat/session/index.vue')['default']
    SessionList: typeof import('./.vitepress/theme/components/@gysm/chat/session-list/index.vue')['default']
    SystemMessage: typeof import('./.vitepress/theme/components/@gysm/chat/message/system-message.vue')['default']
    TaskList: typeof import('./.vitepress/theme/components/task/task-list.vue')['default']
    TestParent: typeof import('./.vitepress/theme/components/test-parent.vue')['default']
    UserMessage: typeof import('./.vitepress/theme/components/@gysm/chat/message/user-message.vue')['default']
  }
}
